# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/mojito-leicacamera/setup-makefiles.sh

BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BOARD_SEPOLICY_DIRS += vendor/xiaomi/mojito-leicacamera/sepolicy
